default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: marat
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: WMS_development

test:
  <<: *default
  database: WMS_test
